/**
 * Deterministic .bax source emitter for MIDI conversion.
 */
import { emitKitLines, type MelodicKitNeed } from './kit.js';
import { compressPlaylist } from './reuse.js';
import type {
  MidiConvertOptions,
  PatternDef,
  SequenceDef,
  ChipRole,
  GmFamily,
} from './types.js';
import type { ReuseResult } from './reuse.js';
import type { AnnotationSource, ArrangementAnnotation } from './arrangement.js';

function formatPatBody(tokens: string[]): string {
  return tokens.join(' ');
}

function familyFromInstName(name: string): GmFamily {
  const m = /^(piano|guitar|bass|strings|pad|lead)/.exec(name);
  return (m?.[1] as GmFamily | undefined) ?? 'lead';
}

function collectMelodicNeeds(reuse: ReuseResult): MelodicKitNeed[] {
  const needs: MelodicKitNeed[] = [];
  const seen = new Set<string>();

  const add = (name: string, role: ChipRole, family: GmFamily) => {
    if (!name || seen.has(name)) return;
    if (['kick', 'snare', 'hihat', 'shaker', 'ghost', 'crash', 'kick_dmc', 'snare_dmc'].includes(name)) return;
    seen.add(name);
    needs.push({ name, role, family });
  };

  const patternByName = new Map(reuse.patterns.map((p) => [p.name, p]));
  const sequenceByName = new Map(reuse.sequences.map((s) => [s.name, s]));

  for (const ch of reuse.channelPlans) {
    if (ch.role === 'noise' || ch.role === 'dmc') continue;
    add(ch.defaultInstrument, ch.role, familyFromInstName(ch.defaultInstrument));

    for (const seqName of ch.sequenceNames) {
      const seq = sequenceByName.get(seqName);
      if (!seq) continue;
      for (const patName of seq.playlist) {
        const pat = patternByName.get(patName);
        if (!pat) continue;
        for (const tok of pat.tokens) {
          const m = /^inst\(([^)]+)\)$/.exec(tok);
          if (!m) continue;
          const name = m[1]!;
          add(name, ch.role, familyFromInstName(name));
        }
      }
    }
  }

  return needs;
}

/** Parse `_sNN_seq` suffix; monolithic `*_seq` → section 0. */
function sectionIndexOfSeqName(name: string): number {
  const m = /_s(\d+)_seq$/.exec(name);
  if (m) return Math.max(0, parseInt(m[1]!, 10) - 1);
  return 0;
}

export const ARRANGEMENT_NOTES_BEGIN = '# >>> arrangement notes';
export const ARRANGEMENT_NOTES_END = '# <<< arrangement notes';

function formatBpm(bpm: number): string {
  return String(Math.round(bpm * 100) / 100);
}

function formatSource(s: AnnotationSource): string {
  const head = s.bars ? `${s.label} -> ${s.instrument}, ${s.bars}` : `${s.label} -> ${s.instrument}`;
  if (s.matched == null) return `${head}: kept ${s.kept}`;
  const reasons: string[] = [];
  if (s.laneOverlap) reasons.push(`lane_overlap ${s.laneOverlap}`);
  if (s.monoReduce) reasons.push(`mono_reduce ${s.monoReduce}`);
  if (s.pitchOutOfRange) reasons.push(`pitch_out_of_range ${s.pitchOutOfRange}`);
  const matched = s.matched + (s.pitchOutOfRange ?? 0);
  let line = `${head}: kept ${s.kept} of ${matched}`;
  if (reasons.length > 0) line += ` (dropped ${reasons.join(', ')})`;
  if (s.filtered) line += `; ignored by include/exclude ${s.filtered}`;
  return line;
}

/** Comment block describing where each channel's notes came from (spec FR-060). */
export function formatArrangementNotes(a: ArrangementAnnotation): string[] {
  const lines: string[] = [ARRANGEMENT_NOTES_BEGIN];
  for (const ch of a.channels) {
    lines.push(`# Channel ${ch.channelIndex} (${ch.role}):`);
    for (const s of ch.sources) lines.push(`#   ${formatSource(s)}`);
    if (ch.role === 'noise' && a.drumHitsDropped > 0) {
      lines.push(`#   drum hits dropped on noise: ${a.drumHitsDropped}`);
    }
  }
  if (a.unplaced.length > 0) {
    lines.push('# Mappings with no output:');
    for (const s of a.unplaced) lines.push(`#   ${formatSource(s)}`);
  }
  if (a.unmappedDropped.length > 0) {
    const parts = a.unmappedDropped.map((u) => `${u.label} (${u.notes} notes)`);
    lines.push(`# Dropped, matching no mapping: ${parts.join(', ')}`);
  }
  const t = a.timing;
  lines.push(
    `# Timing: tempo ${t.policy}, source ${formatBpm(t.sourceBpm)} bpm, written bpm ${Math.round(t.writtenBpm)} ` +
      `(ticksPerBeat ${t.ticksPerBeat})`,
  );
  const window =
    t.startBar == null && t.endBar == null ? 'whole song' : `bars ${t.startBar ?? 1}-${t.endBar ?? 'end'}`;
  lines.push(`# Window: ${window}; nudge ${t.nudge} sixteenth(s)`);
  lines.push(
    `# Ignored: ${t.ignoredTempos} tempo event(s), ${t.ignoredTimeSignatures} time signature event(s)`,
  );
  lines.push(ARRANGEMENT_NOTES_END);
  return lines;
}

export function emitBaxSource(args: {
  options: MidiConvertOptions;
  bpm: number;
  title: string;
  reuse: ReuseResult;
  midiBarComments?: boolean;
  annotation?: ArrangementAnnotation;
}): string {
  const { options, bpm, title, reuse } = args;
  const lines: string[] = [];

  if (args.annotation) {
    lines.push(...formatArrangementNotes(args.annotation));
    lines.push('');
  }
  lines.push(`# Generated by beatbax import midi`);
  lines.push(`# chip=${options.chip} quantize=${options.quantize.mode}/${options.quantize.grid}`);
  lines.push('');
  lines.push(`song name "${title.replace(/"/g, "'")}"`);
  lines.push(`chip ${options.chip}`);
  lines.push(`bpm ${Math.round(bpm)}`);
  lines.push('');

  lines.push('# --- instruments (GM family kit) ---');
  for (const inst of emitKitLines(options.chip, options, collectMelodicNeeds(reuse))) {
    lines.push(inst);
  }
  lines.push('');

  lines.push('# --- patterns ---');
  for (const p of reuse.patterns) {
    if (args.midiBarComments !== false) {
      lines.push(`# bar source index ${p.sourceBarIndex} hash=${p.hash}`);
    }
    lines.push(`pat ${p.name} = ${formatPatBody(p.tokens)}`);
  }
  lines.push('');

  lines.push('# --- sequences ---');
  const sectionCount = Math.max(1, reuse.sectionCount);
  const chunkSize =
    sectionCount === 1
      ? reuse.barsGenerated
      : Math.max(1, options.sectionBars > 0 ? options.sectionBars : reuse.barsGenerated);

  if (sectionCount <= 1) {
    const seqs = [...reuse.sequences].sort((a, b) => a.name.localeCompare(b.name));
    for (const s of seqs) {
      const compressed = compressPlaylist(s.playlist);
      lines.push(`seq ${s.name} = ${compressed.join(' ')}`);
    }
  } else {
    const bySection = new Map<number, SequenceDef[]>();
    for (const s of reuse.sequences) {
      const idx = sectionIndexOfSeqName(s.name);
      const list = bySection.get(idx) ?? [];
      list.push(s);
      bySection.set(idx, list);
    }
    for (let si = 0; si < sectionCount; si++) {
      const barStart = si * chunkSize + 1;
      const barEnd = Math.min(reuse.barsGenerated, (si + 1) * chunkSize);
      lines.push(`# --- Section ${si + 1}: Bars ${barStart}-${barEnd} ---`);
      const seqs = (bySection.get(si) ?? []).sort((a, b) => a.name.localeCompare(b.name));
      for (const s of seqs) {
        const compressed = compressPlaylist(s.playlist);
        lines.push(`seq ${s.name} = ${compressed.join(' ')}`);
      }
      lines.push('');
    }
  }
  if (sectionCount <= 1) lines.push('');

  lines.push('# --- channels ---');
  const chans = [...reuse.channelPlans].sort((a, b) => a.channelIndex - b.channelIndex);
  for (const ch of chans) {
    lines.push(
      `channel ${ch.channelIndex} => inst ${ch.defaultInstrument} seq ${ch.sequenceNames.join(' ')}`,
    );
  }
  lines.push('');
  lines.push('play');
  lines.push('');

  return lines.join('\n');
}

export type { PatternDef, SequenceDef };
