/**
 * Deterministic .bax source emitter for MIDI conversion.
 */
import { emitKitLines, type MelodicKitNeed } from './kit.js';
import { compressPlaylist } from './reuse.js';
import type {
  MidiConvertOptions,
  PatternDef,
  SequenceDef,
  ChipRole,
  GmFamily,
} from './types.js';
import type { ReuseResult } from './reuse.js';

function formatPatBody(tokens: string[]): string {
  return tokens.join(' ');
}

function familyFromInstName(name: string): GmFamily {
  const m = /^(piano|guitar|bass|strings|pad|lead)/.exec(name);
  return (m?.[1] as GmFamily | undefined) ?? 'lead';
}

function collectMelodicNeeds(reuse: ReuseResult): MelodicKitNeed[] {
  const needs: MelodicKitNeed[] = [];
  const seen = new Set<string>();

  const add = (name: string, role: ChipRole, family: GmFamily) => {
    if (!name || seen.has(name)) return;
    if (['kick', 'snare', 'hihat', 'shaker', 'ghost', 'crash', 'kick_dmc', 'snare_dmc'].includes(name)) return;
    seen.add(name);
    needs.push({ name, role, family });
  };

  const patternByName = new Map(reuse.patterns.map((p) => [p.name, p]));
  const sequenceByName = new Map(reuse.sequences.map((s) => [s.name, s]));

  for (const ch of reuse.channelPlans) {
    if (ch.role === 'noise' || ch.role === 'dmc') continue;
    add(ch.defaultInstrument, ch.role, familyFromInstName(ch.defaultInstrument));

    for (const seqName of ch.sequenceNames) {
      const seq = sequenceByName.get(seqName);
      if (!seq) continue;
      for (const patName of seq.playlist) {
        const pat = patternByName.get(patName);
        if (!pat) continue;
        for (const tok of pat.tokens) {
          const m = /^inst\(([^)]+)\)$/.exec(tok);
          if (!m) continue;
          const name = m[1]!;
          add(name, ch.role, familyFromInstName(name));
        }
      }
    }
  }

  return needs;
}

/** Parse `_sNN` suffix; monolithic `*_seq` → section 0. */
function sectionIndexOfSeqName(name: string): number {
  const m = /_s(\d+)$/.exec(name);
  if (m) return Math.max(0, parseInt(m[1]!, 10) - 1);
  return 0;
}

export function emitBaxSource(args: {
  options: MidiConvertOptions;
  bpm: number;
  title: string;
  reuse: ReuseResult;
  midiBarComments?: boolean;
}): string {
  const { options, bpm, title, reuse } = args;
  const lines: string[] = [];

  lines.push(`# Generated by beatbax import midi`);
  lines.push(`# chip=${options.chip} quantize=${options.quantize.mode}/${options.quantize.grid}`);
  lines.push('');
  lines.push(`song name "${title.replace(/"/g, "'")}"`);
  lines.push(`chip ${options.chip}`);
  lines.push(`bpm ${Math.round(bpm)}`);
  lines.push('');

  lines.push('# --- instruments (GM family kit) ---');
  for (const inst of emitKitLines(options.chip, options, collectMelodicNeeds(reuse))) {
    lines.push(inst);
  }
  lines.push('');

  lines.push('# --- patterns ---');
  const pats = [...reuse.patterns].sort((a, b) => a.name.localeCompare(b.name));
  for (const p of pats) {
    if (args.midiBarComments !== false) {
      lines.push(`# bar source index ${p.sourceBarIndex} hash=${p.hash}`);
    }
    lines.push(`pat ${p.name} = ${formatPatBody(p.tokens)}`);
  }
  lines.push('');

  lines.push('# --- sequences ---');
  const sectionCount = Math.max(1, reuse.sectionCount);
  const chunkSize =
    sectionCount === 1
      ? reuse.barsGenerated
      : Math.max(1, options.sectionBars > 0 ? options.sectionBars : reuse.barsGenerated);

  if (sectionCount <= 1) {
    const seqs = [...reuse.sequences].sort((a, b) => a.name.localeCompare(b.name));
    for (const s of seqs) {
      const compressed = compressPlaylist(s.playlist);
      lines.push(`seq ${s.name} = ${compressed.join(' ')}`);
    }
  } else {
    const bySection = new Map<number, SequenceDef[]>();
    for (const s of reuse.sequences) {
      const idx = sectionIndexOfSeqName(s.name);
      const list = bySection.get(idx) ?? [];
      list.push(s);
      bySection.set(idx, list);
    }
    for (let si = 0; si < sectionCount; si++) {
      const barStart = si * chunkSize + 1;
      const barEnd = Math.min(reuse.barsGenerated, (si + 1) * chunkSize);
      lines.push(`# --- Section ${si + 1}: Bars ${barStart}-${barEnd} ---`);
      const seqs = (bySection.get(si) ?? []).sort((a, b) => a.name.localeCompare(b.name));
      for (const s of seqs) {
        const compressed = compressPlaylist(s.playlist);
        lines.push(`seq ${s.name} = ${compressed.join(' ')}`);
      }
      lines.push('');
    }
  }
  if (sectionCount <= 1) lines.push('');

  lines.push('# --- channels ---');
  const chans = [...reuse.channelPlans].sort((a, b) => a.channelIndex - b.channelIndex);
  for (const ch of chans) {
    lines.push(
      `channel ${ch.channelIndex} => inst ${ch.defaultInstrument} seq ${ch.sequenceNames.join(' ')}`,
    );
  }
  lines.push('');
  lines.push('play');
  lines.push('');

  return lines.join('\n');
}

export type { PatternDef, SequenceDef };
