/**
 * Deterministic .bax source emitter for MIDI conversion.
 */
import { emitKitLines } from './kit.js';
import { compressPlaylist } from './reuse.js';
import type {
  MidiConvertOptions,
  PatternDef,
  SequenceDef,
} from './types.js';
import type { ReuseResult } from './reuse.js';

function formatPatBody(tokens: string[]): string {
  // Group into readable chunks of ~4 sounding tokens when possible
  return tokens.join(' ');
}

export function emitBaxSource(args: {
  options: MidiConvertOptions;
  bpm: number;
  title: string;
  reuse: ReuseResult;
  midiBarComments?: boolean;
}): string {
  const { options, bpm, title, reuse } = args;
  const lines: string[] = [];

  lines.push(`# Generated by beatbax import midi`);
  lines.push(`# chip=${options.chip} quantize=${options.quantize.mode}/${options.quantize.grid}`);
  lines.push('');
  lines.push(`song name "${title.replace(/"/g, "'")}"`);
  lines.push(`chip ${options.chip}`);
  lines.push(`bpm ${Math.round(bpm)}`);
  lines.push('');

  lines.push('# --- instruments (default kit) ---');
  for (const inst of emitKitLines(options.chip, options)) {
    lines.push(inst);
  }
  lines.push('');

  lines.push('# --- patterns ---');
  const pats = [...reuse.patterns].sort((a, b) => a.name.localeCompare(b.name));
  for (const p of pats) {
    if (args.midiBarComments !== false) {
      lines.push(`# bar source index ${p.sourceBarIndex} hash=${p.hash}`);
    }
    lines.push(`pat ${p.name} = ${formatPatBody(p.tokens)}`);
  }
  lines.push('');

  lines.push('# --- sequences ---');
  const seqs = [...reuse.sequences].sort((a, b) => a.name.localeCompare(b.name));
  for (const s of seqs) {
    const compressed = compressPlaylist(s.playlist);
    lines.push(`seq ${s.name} = ${compressed.join(' ')}`);
  }
  lines.push('');

  lines.push('# --- channels ---');
  const chans = [...reuse.channelPlans].sort((a, b) => a.channelIndex - b.channelIndex);
  for (const ch of chans) {
    lines.push(`channel ${ch.channelIndex} => inst ${ch.defaultInstrument} seq ${ch.sequenceName}`);
  }
  lines.push('');
  lines.push('play');
  lines.push('');

  return lines.join('\n');
}

export type { PatternDef, SequenceDef };
