import { ARRANGEMENT_NOTES_BEGIN, ARRANGEMENT_NOTES_END } from '../../../src/import/midi';
import { convertWith, expectVerifies, parseResult, rawNote } from './arrangement-helpers';

function quarters(track: number, pitch: number, fromBar: number, toBar: number) {
  const out = [];
  for (let bar = fromBar; bar <= toBar; bar++) {
    for (let beat = 0; beat < 4; beat++) out.push(rawNote(track, pitch, (bar - 1) * 16 + beat * 4, 4));
  }
  return out;
}

function block(source: string): string[] {
  const lines = source.split('\n');
  const start = lines.indexOf(ARRANGEMENT_NOTES_BEGIN);
  const end = lines.indexOf(ARRANGEMENT_NOTES_END);
  return start < 0 || end < 0 ? [] : lines.slice(start, end + 1);
}

const lanesConfig = {
  packing: 'lanes',
  unmappedTracks: 'drop',
  trackMappings: [
    { midiTrack: 5, target: 'pulse1', instrument: 'riff', fromBar: 1, toBar: 2 },
    { midiTrack: 0, target: 'pulse1', instrument: 'vox', fromBar: 3 },
    { midiTrack: 2, target: 'pulse1', instrument: 'gtr' },
  ],
};

describe('089 US6: arrangement notes', () => {
  const parsed = parseResult([...quarters(5, 76, 1, 4), ...quarters(0, 72, 1, 4), ...quarters(2, 64, 1, 4)]);

  test('block opens the file, before the generated header, and the song still verifies', () => {
    const { source } = convertWith(parsed, lanesConfig, 'gameboy', { annotate: true });
    const lines = source.split('\n');
    expect(lines[0]).toBe(ARRANGEMENT_NOTES_BEGIN);
    const end = lines.indexOf(ARRANGEMENT_NOTES_END);
    expect(lines[end + 1]).toBe('');
    expect(lines[end + 2]).toBe('# Generated by beatbax import midi');
    expectVerifies(source);
  });

  test('lists each channel with its mappings in lane order, kept counts and drop reasons', () => {
    const { source } = convertWith(parsed, lanesConfig, 'gameboy', { annotate: true });
    expect(block(source)).toEqual([
      ARRANGEMENT_NOTES_BEGIN,
      '# Channel 1 (pulse1):',
      '#   T5 -> riff, bars 1-2: kept 8 of 8',
      '#   T0 -> vox, bars 3-end: kept 8 of 8',
      '# Mappings with no output:',
      '#   T2 -> gtr, all bars: kept 0 of 16 (dropped lane_overlap 16)',
      '# Dropped, matching no mapping: T0 ch1 (8 notes), T5 ch6 (8 notes)',
      '# Timing: tempo first, source 120 bpm, written bpm 120 (ticksPerBeat 4)',
      '# Window: whole song; nudge 0 sixteenth(s)',
      '# Ignored: 0 tempo event(s), 0 time signature event(s)',
      ARRANGEMENT_NOTES_END,
    ]);
  });

  test('config annotate: true emits the block; absent or false leaves output unchanged', () => {
    const plain = convertWith(parsed, lanesConfig).source;
    expect(plain).not.toContain(ARRANGEMENT_NOTES_BEGIN);
    expect(convertWith(parsed, { ...lanesConfig, annotate: false }).source).toBe(plain);
    const viaConfig = convertWith(parsed, { ...lanesConfig, annotate: true }).source;
    expect(viaConfig.startsWith(ARRANGEMENT_NOTES_BEGIN)).toBe(true);
    // The block is the only difference.
    expect(viaConfig.slice(viaConfig.indexOf('# Generated by beatbax import midi'))).toBe(plain);
  });

  test('mappings that produced no output are listed separately', () => {
    const { source } = convertWith(
      parsed,
      {
        packing: 'lanes',
        trackMappings: [
          { midiTrack: 0, target: 'pulse1', instrument: 'vox' },
          { midiTrack: 7, target: 'pulse2', instrument: 'ghost' },
        ],
      },
      'gameboy',
      { annotate: true },
    );
    const lines = block(source);
    const at = lines.indexOf('# Mappings with no output:');
    expect(at).toBeGreaterThan(0);
    expect(lines[at + 1]).toBe('#   T7 -> ghost, all bars: kept 0 of 0');
  });

  test('mono and pitch-range drops are reported per mapping', () => {
    const chord = [rawNote(0, 60, 0, 4), rawNote(0, 64, 0, 4), rawNote(0, 67, 0, 4), rawNote(0, 20, 4, 4)];
    const { source } = convertWith(
      parseResult(chord),
      { packing: 'lanes', trackMappings: [{ midiTrack: 0, target: 'pulse1', instrument: 'lead', mono: 'highest' }] },
      'gameboy',
      { annotate: true },
    );
    const line = block(source).find((l) => l.startsWith('#   T0 -> lead'));
    expect(line).toMatch(/kept \d+ of 4 \(dropped .*mono_reduce 2/);
  });

  test('timing decisions: override tempo, window, nudge, ignored events', () => {
    const notes = quarters(0, 72, 1, 4);
    const { source } = convertWith(
      parseResult(notes, {
        tempos: [
          { midiTicks: 0, bpm: 200 },
          { midiTicks: 1920, bpm: 96 },
        ],
      }),
      { bpm: 90, ticksPerBeat: 8, patternTicks: 32, startBar: 2, endBar: 3, nudge: -1 },
      'gameboy',
      { annotate: true },
    );
    const lines = block(source);
    expect(lines).toContain('# Timing: tempo override, source 90 bpm, written bpm 180 (ticksPerBeat 8)');
    expect(lines).toContain('# Window: bars 2-3; nudge -1 sixteenth(s)');
    expect(lines).toContain('# Ignored: 2 tempo event(s), 0 time signature event(s)');
    expect(source).toMatch(/^bpm 180$/m);
  });

  test('drum hits lost to noise stack resolution are counted on the noise channel', () => {
    const drum = { isDrum: true, program: 0 };
    const notes = [
      rawNote(9, 36, 0, 1, { ...drum, midiChannel: 9 }),
      rawNote(10, 38, 0, 1, { ...drum, midiChannel: 9 }),
      rawNote(10, 38, 4, 1, { ...drum, midiChannel: 9 }),
    ];
    const { source } = convertWith(
      parseResult(notes),
      {
        trackMappings: [
          { midiTrack: 9, target: 'noise', instrument: 'kit' },
          { midiTrack: 10, target: 'noise', instrument: 'kit' },
        ],
      },
      'gameboy',
      { annotate: true },
    );
    expect(block(source)).toContain('#   drum hits dropped on noise: 1');
  });

  test('deterministic', () => {
    const a = convertWith(parsed, lanesConfig, 'gameboy', { annotate: true }).source;
    const b = convertWith(parsed, lanesConfig, 'gameboy', { annotate: true }).source;
    expect(a).toBe(b);
  });
});
