import type { ChipPlugin, NewSongWizardTemplateOption } from '@beatbax/engine/chips';

export interface NewSongWizardChipOption {
  id: string;
  plugin: ChipPlugin;
}

export interface NewSongWizardCreatePayload {
  source: string;
  songName: string;
}

export interface NewSongWizardController {
  open(): void;
  close(): void;
}

interface NewSongWizardOptions {
  getEnabledChips: () => NewSongWizardChipOption[];
  getDefaultBpm: () => number;
  getDefaultArtist: () => string;
  onCreate: (payload: NewSongWizardCreatePayload) => void;
}

export function claimNewSongWizardOnboarding(
  get: (key: string) => string | undefined,
  set: (key: string, value: string) => void,
  key: string,
): boolean {
  if (get(key) === 'true') return false;
  set(key, 'true');
  return true;
}

// Default fallback image is served from apps/web-ui/public/chip-image.png.
const DEFAULT_FALLBACK_IMAGE = '/chip-image.png';

function normalizeImageSource(raw?: string): string {
  const value = (raw || '').trim();
  if (!value) return DEFAULT_FALLBACK_IMAGE;
  return value;
}

function quoteMetadataValue(value: string): string {
  return JSON.stringify(value);
}

function normalizeTags(raw: string): string {
  return raw
    .split(',')
    .map((tag) => tag.trim())
    .filter(Boolean)
    .join(', ');
}

function validateChipWizardContract(chip: NewSongWizardChipOption): string | null {
  const meta = chip.plugin.newSongWizard?.metadata;
  const templates = chip.plugin.newSongWizard?.templates;
  if (!meta || !templates) return `Chip "${chip.id}" is missing New Song Wizard metadata/templates.`;
  if (!meta.chipDisplayName || !meta.platform || !meta.year || !meta.channelSummary) {
    return `Chip "${chip.id}" has incomplete New Song Wizard metadata.`;
  }
  if (!templates.instruments?.length || !templates.effects?.length || !templates.structure?.length) {
    return `Chip "${chip.id}" has incomplete New Song Wizard templates.`;
  }
  return null;
}

function pickDefaultTemplate(
  templates: NewSongWizardTemplateOption[],
  preferredId?: string,
): NewSongWizardTemplateOption | null {
  if (preferredId) {
    const preferred = templates.find((t) => t.id === preferredId);
    if (preferred) return preferred;
  }
  return templates[0] ?? null;
}

function buildSongSource(params: {
  chipName: string;
  bpm: number;
  songName: string;
  artist: string;
  description: string;
  tags: string;
  instrumentsContent: string;
  effectsContent: string;
  structureContent: string;
}): string {
  const sections: string[] = [];

  const header = ['# Generated by BeatBax New Song Wizard', `chip ${params.chipName}`, `bpm ${params.bpm}`];
  sections.push(header.join('\n'));

  const metadataLines: string[] = [];
  if (params.songName) metadataLines.push(`song name ${quoteMetadataValue(params.songName)}`);
  if (params.artist) metadataLines.push(`song artist ${quoteMetadataValue(params.artist)}`);
  if (params.description) metadataLines.push(`song description ${quoteMetadataValue(params.description)}`);
  const normalizedTags = normalizeTags(params.tags);
  if (normalizedTags) metadataLines.push(`song tags ${quoteMetadataValue(normalizedTags)}`);
  if (metadataLines.length) sections.push(metadataLines.join('\n'));

  if (params.instrumentsContent.trim()) {
    sections.push(`# Example instruments\n${params.instrumentsContent.trim()}`);
  }
  if (params.effectsContent.trim()) {
    sections.push(`# Example named effects\n${params.effectsContent.trim()}`);
  }
  if (params.structureContent.trim()) {
    sections.push(`# Example structure\n${params.structureContent.trim()}`);
  }

  return `${sections.join('\n\n')}\n`;
}

export function buildNewSongWizard(options: NewSongWizardOptions): NewSongWizardController {
  const backdrop = document.createElement('div');
  backdrop.className = 'bb-new-song-wizard-backdrop';
  backdrop.setAttribute('role', 'dialog');
  backdrop.setAttribute('aria-modal', 'true');
  backdrop.setAttribute('aria-label', 'New Song Wizard');

  const modalEl = document.createElement('div');
  modalEl.className = 'bb-new-song-wizard';
  backdrop.appendChild(modalEl);

  const header = document.createElement('div');
  header.className = 'bb-new-song-wizard__header';
  const title = document.createElement('span');
  title.className = 'bb-new-song-wizard__title';
  title.textContent = 'New Song Wizard';
  const closeBtn = document.createElement('button');
  closeBtn.type = 'button';
  closeBtn.className = 'bb-new-song-wizard__close';
  closeBtn.textContent = '✕';
  closeBtn.setAttribute('aria-label', 'Close New Song Wizard');
  header.append(title, closeBtn);

  const body = document.createElement('div');
  body.className = 'bb-new-song-wizard__body';

  const formCol = document.createElement('div');
  formCol.className = 'bb-new-song-wizard__form';

  const errorBanner = document.createElement('div');
  errorBanner.className = 'bb-new-song-wizard__error';
  errorBanner.hidden = true;

  const chipField = document.createElement('div');
  chipField.className = 'bb-new-song-wizard__field';
  const chipLabel = document.createElement('span');
  chipLabel.className = 'bb-new-song-wizard__label';
  chipLabel.textContent = 'Sound chip';
  const chipCarousel = document.createElement('div');
  chipCarousel.className = 'bb-new-song-wizard__chip-carousel';
  const chipPrevBtn = document.createElement('button');
  chipPrevBtn.type = 'button';
  chipPrevBtn.className = 'bb-new-song-wizard__chip-nav bb-new-song-wizard__chip-nav--prev';
  chipPrevBtn.setAttribute('aria-label', 'Previous sound chip');
  chipPrevBtn.textContent = '◀';
  const chipCard = document.createElement('div');
  chipCard.className = 'bb-new-song-wizard__chip-card';
  const summaryImage = document.createElement('img');
  summaryImage.className = 'bb-new-song-wizard__chip-image';
  summaryImage.alt = 'Selected chip platform';
  const chipName = document.createElement('div');
  chipName.className = 'bb-new-song-wizard__chip-name';
  const summaryMeta = document.createElement('div');
  summaryMeta.className = 'bb-new-song-wizard__chip-meta';
  const chipStatus = document.createElement('div');
  chipStatus.className = 'bb-new-song-wizard__chip-status';
  chipStatus.hidden = true;
  chipCard.append(summaryImage, chipName, summaryMeta, chipStatus);
  const chipNextBtn = document.createElement('button');
  chipNextBtn.type = 'button';
  chipNextBtn.className = 'bb-new-song-wizard__chip-nav bb-new-song-wizard__chip-nav--next';
  chipNextBtn.setAttribute('aria-label', 'Next sound chip');
  chipNextBtn.textContent = '▶';
  chipCarousel.append(chipPrevBtn, chipCard, chipNextBtn);
  const chipPagination = document.createElement('div');
  chipPagination.className = 'bb-new-song-wizard__chip-pagination';
  chipField.append(chipLabel, chipCarousel, chipPagination);

  const nameField = document.createElement('label');
  nameField.className = 'bb-new-song-wizard__field';
  nameField.innerHTML = '<span class="bb-new-song-wizard__label">Song name</span>';
  const songNameInput = document.createElement('input');
  songNameInput.type = 'text';
  songNameInput.className = 'bb-new-song-wizard__input';
  songNameInput.placeholder = 'Untitled song';
  nameField.appendChild(songNameInput);

  const artistField = document.createElement('label');
  artistField.className = 'bb-new-song-wizard__field';
  artistField.innerHTML = '<span class="bb-new-song-wizard__label">Song artist</span>';
  const artistInput = document.createElement('input');
  artistInput.type = 'text';
  artistInput.className = 'bb-new-song-wizard__input';
  artistField.appendChild(artistInput);

  const bpmField = document.createElement('label');
  bpmField.className = 'bb-new-song-wizard__field';
  bpmField.innerHTML = '<span class="bb-new-song-wizard__label">BPM</span>';
  const bpmInput = document.createElement('input');
  bpmInput.type = 'number';
  bpmInput.className = 'bb-new-song-wizard__input bb-new-song-wizard__input--sm';
  bpmInput.min = '60';
  bpmInput.max = '300';
  bpmField.appendChild(bpmInput);

  const descField = document.createElement('label');
  descField.className = 'bb-new-song-wizard__field';
  descField.innerHTML = '<span class="bb-new-song-wizard__label">Description</span>';
  const descriptionInput = document.createElement('textarea');
  descriptionInput.className = 'bb-new-song-wizard__textarea';
  descriptionInput.rows = 3;
  descField.appendChild(descriptionInput);

  const tagsField = document.createElement('label');
  tagsField.className = 'bb-new-song-wizard__field';
  tagsField.innerHTML = '<span class="bb-new-song-wizard__label">Tags (optional)</span>';
  const tagsInput = document.createElement('input');
  tagsInput.type = 'text';
  tagsInput.className = 'bb-new-song-wizard__input';
  tagsInput.placeholder = 'demo, upbeat';
  tagsField.appendChild(tagsInput);

  const rowNameArtist = document.createElement('div');
  rowNameArtist.className = 'bb-new-song-wizard__field-grid';
  rowNameArtist.append(nameField, artistField);

  const exampleOptionsField = document.createElement('div');
  exampleOptionsField.className = 'bb-new-song-wizard__field bb-new-song-wizard__toggle-group';

  function createExampleToggle(label: string, ariaLabel: string): { row: HTMLLabelElement; input: HTMLInputElement } {
    const row = document.createElement('label');
    row.className = 'bb-settings-row bb-settings-toggle-row bb-new-song-wizard__toggle';
    const text = document.createElement('span');
    text.className = 'bb-settings-label';
    text.textContent = label;
    const input = document.createElement('input');
    input.type = 'checkbox';
    input.className = 'bb-settings-toggle';
    input.setAttribute('aria-label', ariaLabel);
    row.append(text, input);
    return { row, input };
  }

  const instrumentsToggle = createExampleToggle('Create example instruments', 'Create example instruments');
  const effectsToggle = createExampleToggle('Create named effects', 'Create named effects');
  const structureToggle = createExampleToggle('Create example structure', 'Create example structure');
  exampleOptionsField.append(instrumentsToggle.row, effectsToggle.row, structureToggle.row);

  // Create a container for the BPM field to align it in the first column
  const bpmRow = document.createElement('div');
  bpmRow.className = 'bb-new-song-wizard__field-grid'; // Assuming this class supports two-column layout
  bpmRow.appendChild(bpmField);

  // Create a container for the example toggles to align them in the second column
  const exampleTogglesRow = document.createElement('div');
  exampleTogglesRow.className = 'bb-new-song-wizard__field-grid'; // Assuming this class supports two-column layout
  exampleTogglesRow.append(
    instrumentsToggle.row,
    effectsToggle.row,
    structureToggle.row
  );

  formCol.append(
    errorBanner,
    chipField,
    rowNameArtist,
    descField,
    tagsField,
    bpmRow, // Append the BPM container
    exampleTogglesRow, // Append the toggles container
  );

  body.append(formCol);

  const footer = document.createElement('div');
  footer.className = 'bb-new-song-wizard__footer';
  const cancelBtn = document.createElement('button');
  cancelBtn.type = 'button';
  cancelBtn.className = 'bb-new-song-wizard__btn bb-new-song-wizard__btn--secondary';
  cancelBtn.textContent = 'Cancel';
  const createBtn = document.createElement('button');
  createBtn.type = 'button';
  createBtn.className = 'bb-new-song-wizard__btn bb-new-song-wizard__btn--primary';
  createBtn.textContent = 'Create Song';
  footer.append(cancelBtn, createBtn);

  modalEl.append(header, body, footer);
  document.body.appendChild(backdrop);

  let chips: NewSongWizardChipOption[] = [];
  let selectedChipId = '';
  let bodyOverflowBeforeOpen = '';
  const selectedExamples: Record<'instruments' | 'effects' | 'structure', NewSongWizardTemplateOption | null> = {
    instruments: null,
    effects: null,
    structure: null,
  };

  function currentChip(): NewSongWizardChipOption | undefined {
    return chips.find((chip) => chip.id === selectedChipId);
  }

  function selectedChipIndex(): number {
    return chips.findIndex((chip) => chip.id === selectedChipId);
  }

  function selectChipAt(index: number): void {
    if (!chips.length) {
      selectedChipId = '';
      return;
    }
    const wrapped = (index + chips.length) % chips.length;
    selectedChipId = chips[wrapped].id;
  }

  function renderSelectedChip(): void {
    const selected = currentChip();
    const issue = selected ? validateChipWizardContract(selected) : 'No enabled chip plugins found.';
    if (!selected || issue) {
      summaryImage.src = DEFAULT_FALLBACK_IMAGE;
      chipName.textContent = selected?.id ?? 'No chip selected';
      summaryMeta.textContent = issue ?? 'No chip selected.';
      chipStatus.hidden = !issue;
      chipStatus.textContent = issue ?? '';
      errorBanner.hidden = false;
      errorBanner.textContent = issue ?? '';
      createBtn.disabled = true;
      selectedExamples.instruments = null;
      selectedExamples.effects = null;
      selectedExamples.structure = null;
      instrumentsToggle.input.checked = false;
      effectsToggle.input.checked = false;
      structureToggle.input.checked = false;
      instrumentsToggle.input.disabled = true;
      effectsToggle.input.disabled = true;
      structureToggle.input.disabled = true;
      return;
    }

    errorBanner.hidden = true;
    createBtn.disabled = false;
    chipStatus.hidden = true;
    chipStatus.textContent = '';
    const wizard = selected.plugin.newSongWizard!;
    summaryImage.src = normalizeImageSource(wizard.metadata.image);
    chipName.textContent = wizard.metadata.chipDisplayName;
    summaryMeta.innerHTML = [
      `<div>${wizard.metadata.platform}</div>`,
      `<div>Year: ${wizard.metadata.year}</div>`,
      `<div>Channels: ${wizard.metadata.channelSummary}</div>`,
    ].join('');

    selectedExamples.instruments = pickDefaultTemplate(wizard.templates.instruments, wizard.templates.defaults?.instruments);
    selectedExamples.effects = pickDefaultTemplate(wizard.templates.effects, wizard.templates.defaults?.effects);
    selectedExamples.structure = pickDefaultTemplate(wizard.templates.structure, wizard.templates.defaults?.structure);

    instrumentsToggle.input.disabled = !selectedExamples.instruments;
    effectsToggle.input.disabled = !selectedExamples.effects;
    structureToggle.input.disabled = !selectedExamples.structure;

    instrumentsToggle.input.checked = !!selectedExamples.instruments;
    effectsToggle.input.checked = !!selectedExamples.effects;
    structureToggle.input.checked = !!selectedExamples.structure;
  }

  function renderChipNavigator(): void {
    if (chips.length > 0 && !currentChip()) {
      selectedChipId = chips[0].id;
    }
    const index = selectedChipIndex();
    chipPagination.textContent = chips.length > 0
      ? `${Math.max(index, 0) + 1} / ${chips.length}`
      : '0 / 0';
    const navDisabled = chips.length <= 1;
    chipPrevBtn.disabled = navDisabled;
    chipNextBtn.disabled = navDisabled;
  }

  function refreshOpenDefaults(): void {
    chips = options.getEnabledChips();
    selectedChipId = chips[0]?.id ?? '';
    artistInput.value = options.getDefaultArtist();
    bpmInput.value = String(options.getDefaultBpm());
    songNameInput.value = '';
    descriptionInput.value = '';
    tagsInput.value = '';
    renderChipNavigator();
    renderSelectedChip();
  }

  function open(): void {
    refreshOpenDefaults();
    bodyOverflowBeforeOpen = document.body.style.overflow;
    document.body.style.overflow = 'hidden';
    backdrop.classList.add('bb-new-song-wizard-backdrop--open');
    (songNameInput as HTMLElement).focus();
  }

  function close(): void {
    backdrop.classList.remove('bb-new-song-wizard-backdrop--open');
    document.body.style.overflow = bodyOverflowBeforeOpen;
  }

  createBtn.addEventListener('click', () => {
    const selected = currentChip();
    if (!selected || validateChipWizardContract(selected)) return;
    const bpmRaw = Number(bpmInput.value);
    const bpm = Number.isFinite(bpmRaw) ? Math.min(300, Math.max(60, bpmRaw)) : 128;
    const songName = songNameInput.value.trim();
    const source = buildSongSource({
      chipName: selected.plugin.name,
      bpm,
      songName: songName || 'Untitled song',
      artist: artistInput.value.trim(),
      description: descriptionInput.value.trim(),
      tags: tagsInput.value.trim(),
      instrumentsContent: instrumentsToggle.input.checked ? (selectedExamples.instruments?.content ?? '') : '',
      effectsContent: effectsToggle.input.checked ? (selectedExamples.effects?.content ?? '') : '',
      structureContent: structureToggle.input.checked ? (selectedExamples.structure?.content ?? '') : '',
    });
    close();
    options.onCreate({ source, songName: songName || 'Untitled song' });
  });

  cancelBtn.addEventListener('click', close);
  closeBtn.addEventListener('click', close);
  backdrop.addEventListener('click', (e) => {
    if (e.target === backdrop) close();
  });
  chipPrevBtn.addEventListener('click', () => {
    selectChipAt(selectedChipIndex() - 1);
    renderChipNavigator();
    renderSelectedChip();
  });
  chipNextBtn.addEventListener('click', () => {
    selectChipAt(selectedChipIndex() + 1);
    renderChipNavigator();
    renderSelectedChip();
  });
  backdrop.addEventListener('keydown', (e) => {
    if (e.key === 'Escape') {
      e.stopPropagation();
      close();
      return;
    }

    const keyTarget = e.target as HTMLElement | null;
    const isTextEntryTarget = !!keyTarget && (
      keyTarget.tagName === 'INPUT' ||
      keyTarget.tagName === 'TEXTAREA' ||
      keyTarget.tagName === 'SELECT' ||
      keyTarget.isContentEditable
    );

    if (!isTextEntryTarget && !chipPrevBtn.disabled && !chipNextBtn.disabled) {
      if (e.key === 'ArrowLeft') {
        e.preventDefault();
        selectChipAt(selectedChipIndex() - 1);
        renderChipNavigator();
        renderSelectedChip();
        return;
      }
      if (e.key === 'ArrowRight') {
        e.preventDefault();
        selectChipAt(selectedChipIndex() + 1);
        renderChipNavigator();
        renderSelectedChip();
        return;
      }
    }

    if (e.key !== 'Tab') return;
    const focusable = Array.from(
      modalEl.querySelectorAll<HTMLElement>(
        'button:not([disabled]), input:not([disabled]), textarea:not([disabled])',
      ),
    );
    if (!focusable.length) return;
    const first = focusable[0];
    const last = focusable[focusable.length - 1];
    if (e.shiftKey && document.activeElement === first) {
      e.preventDefault();
      last.focus();
    } else if (!e.shiftKey && document.activeElement === last) {
      e.preventDefault();
      first.focus();
    }
  });

  return { open, close };
}
