import type { ChipPlugin, NewSongWizardTemplateOption } from '@beatbax/engine/chips';

export interface NewSongWizardChipOption {
  id: string;
  plugin: ChipPlugin;
}

export interface NewSongWizardCreatePayload {
  source: string;
  songName: string;
}

export interface NewSongWizardController {
  open(): void;
  close(): void;
}

interface NewSongWizardOptions {
  getEnabledChips: () => NewSongWizardChipOption[];
  getDefaultBpm: () => number;
  getDefaultArtist: () => string;
  onCreate: (payload: NewSongWizardCreatePayload) => void;
  onOpenExisting: () => void;
}

export function claimNewSongWizardOnboarding(
  get: (key: string) => string | undefined,
  set: (key: string, value: string) => void,
  key: string,
): boolean {
  if (get(key) === 'true') return false;
  set(key, 'true');
  return true;
}

const DEFAULT_FALLBACK_IMAGE =
  'data:image/svg+xml;utf8,' +
  encodeURIComponent(
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 160 96">' +
    '<rect width="160" height="96" fill="#2b2b2b"/>' +
    '<rect x="12" y="12" width="136" height="72" rx="8" fill="#1f1f1f" stroke="#555"/>' +
    '<rect x="26" y="28" width="108" height="8" rx="3" fill="#666"/>' +
    '<rect x="26" y="44" width="84" height="8" rx="3" fill="#555"/>' +
    '<rect x="26" y="60" width="64" height="8" rx="3" fill="#4c4c4c"/>' +
    '</svg>',
  );

function quoteMetadataValue(value: string): string {
  return JSON.stringify(value);
}

function normalizeTags(raw: string): string {
  return raw
    .split(',')
    .map((tag) => tag.trim())
    .filter(Boolean)
    .join(', ');
}

function validateChipWizardContract(chip: NewSongWizardChipOption): string | null {
  const meta = chip.plugin.newSongWizard?.metadata;
  const templates = chip.plugin.newSongWizard?.templates;
  if (!meta || !templates) return `Chip "${chip.id}" is missing New Song Wizard metadata/templates.`;
  if (!meta.chipDisplayName || !meta.platform || !meta.year || !meta.channelSummary) {
    return `Chip "${chip.id}" has incomplete New Song Wizard metadata.`;
  }
  if (!templates.instruments?.length || !templates.namedEffects?.length || !templates.structure?.length) {
    return `Chip "${chip.id}" has incomplete New Song Wizard templates.`;
  }
  return null;
}

function pickTemplateById(
  templates: NewSongWizardTemplateOption[],
  id: string,
): NewSongWizardTemplateOption | null {
  return templates.find((t) => t.id === id) ?? null;
}

function buildSongSource(params: {
  chipName: string;
  bpm: number;
  songName: string;
  artist: string;
  description: string;
  tags: string;
  instrumentsTemplate: NewSongWizardTemplateOption | null;
  namedEffectsTemplate: NewSongWizardTemplateOption | null;
  structureTemplate: NewSongWizardTemplateOption | null;
}): string {
  const sections: string[] = [];

  const header = ['# Generated by BeatBax New Song Wizard', `chip ${params.chipName}`, `bpm ${params.bpm}`];
  sections.push(header.join('\n'));

  const metadataLines: string[] = [];
  if (params.songName) metadataLines.push(`song name ${quoteMetadataValue(params.songName)}`);
  if (params.artist) metadataLines.push(`song artist ${quoteMetadataValue(params.artist)}`);
  if (params.description) metadataLines.push(`song description ${quoteMetadataValue(params.description)}`);
  const normalizedTags = normalizeTags(params.tags);
  if (normalizedTags) metadataLines.push(`song tags ${quoteMetadataValue(normalizedTags)}`);
  if (metadataLines.length) sections.push(metadataLines.join('\n'));

  if (params.instrumentsTemplate?.content.trim()) {
    sections.push(`# Instruments template: ${params.instrumentsTemplate.label}\n${params.instrumentsTemplate.content.trim()}`);
  }
  if (params.namedEffectsTemplate?.content.trim()) {
    sections.push(`# Named effects template: ${params.namedEffectsTemplate.label}\n${params.namedEffectsTemplate.content.trim()}`);
  }
  if (params.structureTemplate?.content.trim()) {
    sections.push(`# Structure template: ${params.structureTemplate.label}\n${params.structureTemplate.content.trim()}`);
  } else {
    sections.push(['pat melody = C5 E5 G5 C6', 'seq main = melody', 'channel 1 => seq main', 'play'].join('\n'));
  }

  return `${sections.join('\n\n')}\n`;
}

export function buildNewSongWizard(options: NewSongWizardOptions): NewSongWizardController {
  const backdrop = document.createElement('div');
  backdrop.className = 'bb-new-song-wizard-backdrop';
  backdrop.setAttribute('role', 'dialog');
  backdrop.setAttribute('aria-modal', 'true');
  backdrop.setAttribute('aria-label', 'New Song Wizard');

  const modalEl = document.createElement('div');
  modalEl.className = 'bb-new-song-wizard';
  backdrop.appendChild(modalEl);

  const header = document.createElement('div');
  header.className = 'bb-new-song-wizard__header';
  const title = document.createElement('span');
  title.className = 'bb-new-song-wizard__title';
  title.textContent = '🎼  New Song Wizard';
  const closeBtn = document.createElement('button');
  closeBtn.type = 'button';
  closeBtn.className = 'bb-new-song-wizard__close';
  closeBtn.textContent = '✕';
  closeBtn.setAttribute('aria-label', 'Close New Song Wizard');
  header.append(title, closeBtn);

  const body = document.createElement('div');
  body.className = 'bb-new-song-wizard__body';

  const formCol = document.createElement('div');
  formCol.className = 'bb-new-song-wizard__form';
  const sideCol = document.createElement('div');
  sideCol.className = 'bb-new-song-wizard__side';

  const errorBanner = document.createElement('div');
  errorBanner.className = 'bb-new-song-wizard__error';
  errorBanner.hidden = true;

  const chipField = document.createElement('div');
  chipField.className = 'bb-new-song-wizard__field';
  const chipLabel = document.createElement('span');
  chipLabel.className = 'bb-new-song-wizard__label';
  chipLabel.textContent = 'Sound chip';
  const chipList = document.createElement('div');
  chipList.className = 'bb-new-song-wizard__chip-list';
  chipField.append(chipLabel, chipList);

  const nameField = document.createElement('label');
  nameField.className = 'bb-new-song-wizard__field';
  nameField.innerHTML = '<span class="bb-new-song-wizard__label">Song name</span>';
  const songNameInput = document.createElement('input');
  songNameInput.type = 'text';
  songNameInput.className = 'bb-new-song-wizard__input';
  songNameInput.placeholder = 'Untitled song';
  nameField.appendChild(songNameInput);

  const artistField = document.createElement('label');
  artistField.className = 'bb-new-song-wizard__field';
  artistField.innerHTML = '<span class="bb-new-song-wizard__label">Song artist</span>';
  const artistInput = document.createElement('input');
  artistInput.type = 'text';
  artistInput.className = 'bb-new-song-wizard__input';
  artistField.appendChild(artistInput);

  const bpmField = document.createElement('label');
  bpmField.className = 'bb-new-song-wizard__field';
  bpmField.innerHTML = '<span class="bb-new-song-wizard__label">BPM</span>';
  const bpmInput = document.createElement('input');
  bpmInput.type = 'number';
  bpmInput.className = 'bb-new-song-wizard__input bb-new-song-wizard__input--sm';
  bpmInput.min = '60';
  bpmInput.max = '300';
  bpmField.appendChild(bpmInput);

  const descField = document.createElement('label');
  descField.className = 'bb-new-song-wizard__field';
  descField.innerHTML = '<span class="bb-new-song-wizard__label">Description</span>';
  const descriptionInput = document.createElement('textarea');
  descriptionInput.className = 'bb-new-song-wizard__textarea';
  descriptionInput.rows = 3;
  descField.appendChild(descriptionInput);

  const tagsField = document.createElement('label');
  tagsField.className = 'bb-new-song-wizard__field';
  tagsField.innerHTML = '<span class="bb-new-song-wizard__label">Tags (optional)</span>';
  const tagsInput = document.createElement('input');
  tagsInput.type = 'text';
  tagsInput.className = 'bb-new-song-wizard__input';
  tagsInput.placeholder = 'demo, upbeat';
  tagsField.appendChild(tagsInput);

  const instrumentsField = document.createElement('label');
  instrumentsField.className = 'bb-new-song-wizard__field';
  instrumentsField.innerHTML = '<span class="bb-new-song-wizard__label">Create instruments</span>';
  const instrumentsSelect = document.createElement('select');
  instrumentsSelect.className = 'bb-new-song-wizard__select';
  instrumentsField.appendChild(instrumentsSelect);

  const effectsField = document.createElement('label');
  effectsField.className = 'bb-new-song-wizard__field';
  effectsField.innerHTML = '<span class="bb-new-song-wizard__label">Create named effects</span>';
  const effectsSelect = document.createElement('select');
  effectsSelect.className = 'bb-new-song-wizard__select';
  effectsField.appendChild(effectsSelect);

  const structureField = document.createElement('label');
  structureField.className = 'bb-new-song-wizard__field';
  structureField.innerHTML = '<span class="bb-new-song-wizard__label">Create structure</span>';
  const structureSelect = document.createElement('select');
  structureSelect.className = 'bb-new-song-wizard__select';
  structureField.appendChild(structureSelect);

  formCol.append(
    errorBanner,
    chipField,
    nameField,
    artistField,
    bpmField,
    descField,
    tagsField,
    instrumentsField,
    effectsField,
    structureField,
  );

  const summaryTitle = document.createElement('h3');
  summaryTitle.className = 'bb-new-song-wizard__summary-title';
  summaryTitle.textContent = 'Chip summary';
  const summaryImage = document.createElement('img');
  summaryImage.className = 'bb-new-song-wizard__summary-image';
  summaryImage.alt = 'Selected chip platform';
  const summaryMeta = document.createElement('div');
  summaryMeta.className = 'bb-new-song-wizard__summary-meta';
  sideCol.append(summaryTitle, summaryImage, summaryMeta);

  body.append(formCol, sideCol);

  const footer = document.createElement('div');
  footer.className = 'bb-new-song-wizard__footer';
  const openExistingBtn = document.createElement('button');
  openExistingBtn.type = 'button';
  openExistingBtn.className = 'bb-new-song-wizard__btn bb-new-song-wizard__btn--secondary';
  openExistingBtn.textContent = 'Open Existing Song';
  const createBtn = document.createElement('button');
  createBtn.type = 'button';
  createBtn.className = 'bb-new-song-wizard__btn bb-new-song-wizard__btn--primary';
  createBtn.textContent = 'Create New Song';
  footer.append(openExistingBtn, createBtn);

  modalEl.append(header, body, footer);
  document.body.appendChild(backdrop);

  let chips: NewSongWizardChipOption[] = [];
  let selectedChipId = '';

  function currentChip(): NewSongWizardChipOption | undefined {
    return chips.find((chip) => chip.id === selectedChipId);
  }

  function populateSelect(
    select: HTMLSelectElement,
    optionsList: NewSongWizardTemplateOption[],
    selected: string | undefined,
  ): void {
    select.innerHTML = '';
    const none = document.createElement('option');
    none.value = '__none__';
    none.textContent = 'None';
    select.appendChild(none);
    for (const opt of optionsList) {
      const el = document.createElement('option');
      el.value = opt.id;
      el.textContent = opt.label;
      select.appendChild(el);
    }
    select.value = selected && optionsList.some((o) => o.id === selected) ? selected : none.value;
  }

  function renderSelectedChip(): void {
    const selected = currentChip();
    const issue = selected ? validateChipWizardContract(selected) : 'No enabled chip plugins found.';
    if (!selected || issue) {
      summaryImage.src = DEFAULT_FALLBACK_IMAGE;
      summaryMeta.textContent = issue ?? 'No chip selected.';
      errorBanner.hidden = false;
      errorBanner.textContent = issue ?? '';
      createBtn.disabled = true;
      populateSelect(instrumentsSelect, [], undefined);
      populateSelect(effectsSelect, [], undefined);
      populateSelect(structureSelect, [], undefined);
      return;
    }

    errorBanner.hidden = true;
    createBtn.disabled = false;
    const wizard = selected.plugin.newSongWizard!;
    summaryImage.src = wizard.metadata.image || DEFAULT_FALLBACK_IMAGE;
    summaryMeta.innerHTML = [
      `<div><strong>${wizard.metadata.chipDisplayName}</strong></div>`,
      `<div>${wizard.metadata.platform}</div>`,
      `<div>Year: ${wizard.metadata.year}</div>`,
      `<div>Channels: ${wizard.metadata.channelSummary}</div>`,
    ].join('');

    populateSelect(instrumentsSelect, wizard.templates.instruments, wizard.templates.defaults?.instruments);
    populateSelect(effectsSelect, wizard.templates.namedEffects, wizard.templates.defaults?.namedEffects);
    populateSelect(structureSelect, wizard.templates.structure, wizard.templates.defaults?.structure);
  }

  function renderChipNavigator(): void {
    chipList.innerHTML = '';
    for (const chip of chips) {
      const issue = validateChipWizardContract(chip);
      const chipName = chip.plugin.newSongWizard?.metadata.chipDisplayName ?? chip.id;
      const row = document.createElement('label');
      row.className = 'bb-new-song-wizard__chip-row';
      const input = document.createElement('input');
      input.type = 'radio';
      input.name = 'bb-new-song-chip';
      input.value = chip.id;
      input.checked = chip.id === selectedChipId;
      input.addEventListener('change', () => {
        selectedChipId = chip.id;
        renderSelectedChip();
      });
      const text = document.createElement('span');
      text.textContent = chipName;
      row.append(input, text);
      if (issue) {
        const warn = document.createElement('span');
        warn.className = 'bb-new-song-wizard__chip-warning';
        warn.textContent = 'missing metadata';
        row.appendChild(warn);
      }
      chipList.appendChild(row);
    }
  }

  function refreshOpenDefaults(): void {
    chips = options.getEnabledChips();
    selectedChipId = chips[0]?.id ?? '';
    artistInput.value = options.getDefaultArtist();
    bpmInput.value = String(options.getDefaultBpm());
    songNameInput.value = '';
    descriptionInput.value = '';
    tagsInput.value = '';
    renderChipNavigator();
    renderSelectedChip();
  }

  function open(): void {
    refreshOpenDefaults();
    backdrop.classList.add('bb-new-song-wizard-backdrop--open');
    (songNameInput as HTMLElement).focus();
  }

  function close(): void {
    backdrop.classList.remove('bb-new-song-wizard-backdrop--open');
  }

  createBtn.addEventListener('click', () => {
    const selected = currentChip();
    if (!selected || validateChipWizardContract(selected)) return;
    const wizard = selected.plugin.newSongWizard!;
    const bpmRaw = Number(bpmInput.value);
    const bpm = Number.isFinite(bpmRaw) ? Math.min(300, Math.max(60, bpmRaw)) : 128;
    const instrumentsTemplate = instrumentsSelect.value === '__none__'
      ? null
      : pickTemplateById(wizard.templates.instruments, instrumentsSelect.value);
    const namedEffectsTemplate = effectsSelect.value === '__none__'
      ? null
      : pickTemplateById(wizard.templates.namedEffects, effectsSelect.value);
    const structureTemplate = structureSelect.value === '__none__'
      ? null
      : pickTemplateById(wizard.templates.structure, structureSelect.value);
    const songName = songNameInput.value.trim();
    const source = buildSongSource({
      chipName: selected.plugin.name,
      bpm,
      songName,
      artist: artistInput.value.trim(),
      description: descriptionInput.value.trim(),
      tags: tagsInput.value.trim(),
      instrumentsTemplate,
      namedEffectsTemplate,
      structureTemplate,
    });
    close();
    options.onCreate({ source, songName });
  });

  openExistingBtn.addEventListener('click', () => {
    close();
    options.onOpenExisting();
  });
  closeBtn.addEventListener('click', close);
  backdrop.addEventListener('click', (e) => {
    if (e.target === backdrop) close();
  });
  backdrop.addEventListener('keydown', (e) => {
    if (e.key === 'Escape') {
      e.stopPropagation();
      close();
      return;
    }
    if (e.key !== 'Tab') return;
    const focusable = Array.from(
      modalEl.querySelectorAll<HTMLElement>(
        'button:not([disabled]), input:not([disabled]), select:not([disabled]), textarea:not([disabled])',
      ),
    );
    if (!focusable.length) return;
    const first = focusable[0];
    const last = focusable[focusable.length - 1];
    if (e.shiftKey && document.activeElement === first) {
      e.preventDefault();
      last.focus();
    } else if (!e.shiftKey && document.activeElement === last) {
      e.preventDefault();
      first.focus();
    }
  });

  return { open, close };
}
